import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import data from '../component/data.json'
import { useState } from 'react'

export default function Home(props) {
  let eng = props.eng
  
  return (
    <div className={styles.container}>
      <Head>
        <title>{eng ? data.eng.site : data.fr.site}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        {eng ? data.eng.welcome : data.fr.welcome}
        </h1>

        {/* <p className={styles.description}>
          Got an account? Please <a className={styles.aTag} href="/login">Login</a>
        </p> */}
        <form className={styles.form}>
          <div>
            <p className={styles.description}>{eng ? data.eng.form : data.fr.form}</p>

            <label><b className={styles.description}>{eng ? data.eng.user : data.fr.user}</b></label>
            <input type="text" placeholder={eng ? data.eng.enterUser : data.fr.enterUser} name="username" id="username" required />

            <label><b className={styles.description}>{eng ? data.eng.email : data.fr.email}</b></label>
            <input type="text" placeholder={eng ? data.eng.enterEmail : data.fr.enterEmail} name="email" id="email" required />

            <label><b className={styles.description}>{eng ? data.eng.password : data.fr.password}</b></label>
            <input type="text" placeholder={eng ? data.eng.enterPassword : data.fr.enterPassword} name="password" id="password" required />

            <button type="submit" className={styles.registerbtn}><h1>{eng ? data.eng.save : data.fr.save}</h1></button>

          </div>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
